import Head from 'next/head'
import React from 'react'
import Image from 'next/image'

import style from '@/styles/Home.module.css'

import Footer from './components/Footer'

// Images
import Diamond_Blue from '../public/images/About/Diamond_Blue.svg'
import blog_main_02 from '../public/images/About/blog-main-02.jpg'
import media_1 from '../public/images/About/media-1.jpeg'
import media_2 from '../public/images/About/media-2.jpeg'


export default function About() {
    return (
        <>

            <Head>
                <title>Nuestra Historia</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={style.overflow}>

                {/* S1 */}
                <div className={`${style.section} ${style.home_hero}`}>
                    <div className={style.container_large}>
                        <div id={style['Portfolio-1']}>
                            <div className={style.container}>
                                <h2 className={style.centered}>
                                    Nuestra Historia
                                </h2>
                                <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                                    <Image
                                        src={Diamond_Blue}
                                        loading="lazy"
                                        alt=""
                                    />
                                    <div className={`${style.decorative_line} ${style.blue}`} />
                                </div>
                                <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* S2 */}
                <div className={style.detail_hero}>
                    <div className={`${style.container} ${style.w_container}`}>
                        <Image
                            src={blog_main_02}
                            loading="eager"
                            alt=""
                            sizes="(max-width: 479px) 94vw, (max-width: 767px) 96vw, 97vw"
                            className={style.full_image}
                        />
                    </div>
                </div>

                {/* S3 */}
                <div className={style.detail_section}>
                    <div className={`${style.container} ${style.w_container}`}>
                        <div className={`${style.blog_rich_content} ${style.w_richtext}`}>
                            <p>
                                Text de Prueba Text de Prueba Text de Prueba Text de PruebaText de Prueba
                                Text de Prueba Text de Prueba Text de Prueba Text de PruebaText de Prueba
                                Text de Prueba Text de Prueba Text de Prueba Text de PruebaText de Prueba
                            </p>
                            <figure
                                className={`${style.w_richtext_figure_type_image} ${style.w_richtext_align_fullwidth}`}
                                style={{ maxWidth: "900pxpx" }}
                            >
                                <div>
                                    <Image
                                        src={media_1}
                                        loading="lazy"
                                        alt="Sample Image"
                                    />
                                </div>
                            </figure>
                            <blockquote>
                                “ Text de Prueba Text de Prueba Text de Prueba Text de PruebaText de Prueba Text de Prueba ”
                            </blockquote>
                            <h2>Titulo Titulo</h2>
                            <ul role="list">
                                <li>
                                    Sit vulputate aliquam cras aliquam. Et, nibh congue consequat
                                    pellentesque.
                                </li>
                                <li>
                                    Vestibulum massa aliquet odio mauris duis amet. In sed dapibus porta
                                    est amet.
                                </li>
                                <li>
                                    Urna augue arcu duis eget proin sed morbi. Purus sit nunc sodales
                                    aliquam.
                                </li>
                                <li>
                                    Tortor tellus commodo volutpat sed vel enim. Mi justo, proin
                                    volutpat turpis aet.
                                </li>
                            </ul>
                            <h3>Titulo</h3>
                            <ol role="list">
                                <li>
                                    Nibh libero condimentum duis turpis pretium molestie netus turpis
                                </li>
                                <li>Turpis lacus sed sagittis mollis sitquam ipsum</li>
                                <li>Feugiat maurisac ultricies cursus sollicitudin acmauris</li>
                                <li>
                                    Arcu rutrum luctus libero elementum quis libero enim utgravida quis
                                </li>
                            </ol>
                            <figure
                                className={`${style.w_richtext_figure_type_image} ${style.w_richtext_align_fullwidth}`}
                                style={{ maxWidth: "900pxpx" }}
                            >
                                <div>
                                    <Image
                                        src={media_2}
                                        loading="lazy"
                                        alt="Sample Image"
                                    />
                                </div>
                            </figure>
                            <h4>Titulo</h4>
                            <p>
                                Text de PruebaText de PruebaText de PruebaText de Prueba Text de Prueba Text de Prueba
                                Text de Prueba Text de PruebaText de Prueba
                            </p>
                            <ul role="list">
                                <li>
                                    Sit vulputate aliquam cras aliquam etnibh congue consequat
                                    pellentesque
                                </li>
                                <li>
                                    Vestibulum massa aliquet odio mauris duis amet nsed dapibus porta
                                    est amet
                                </li>
                                <li>
                                    Urna augue arcu duis eget proin sed morbi purus sit nunc sodales
                                    aliquam
                                </li>
                            </ul>
                            <h5>Titulo Titlulo</h5>
                            <p>
                                Ultrices amet magna senectus in nulla. Lobortis a orci arcu lorem id
                                turpis et. Dolor, euismod facilisis nisi, varius ipsum quam velit.
                                Diam risus, consequat sapien leo vulputate amet in.
                            </p>
                            <h6>Titulo Titulo</h6>
                            <p>
                                Non eget eu dolor non convallis. Facilisi tellus a faucibus a enim. Ac
                                duis egestas senectus posuere diam sapien. Suspendisse neque venenatis
                                id nibh enim lectus egestas.
                            </p>
                        </div>
                    </div>
                </div>

                <Footer />

            </div>
        </>
    )
}
