import Head from 'next/head'
import Image from 'next/image'
import style from '@/styles/Home.module.css'
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useEffect, useLayoutEffect, useRef } from 'react';
import Link from 'next/link';

import Footer from './components/Footer';

import { Gallery, Item } from 'react-photoswipe-gallery'
import 'photoswipe/style.css';

// Images 
import home_1 from '../public/images/Home/home1_506x569.jpg'
import home_2 from '../public/images/Home/home2_429x360.jpg'
import home_3 from '../public/images/Home/home3_703x712.jpg'
import arrow from '../public/images/Home/arrow.svg'
import stylish_pools from '../public/images/Home/stylish-pools.png'
import exquisite_foods from '../public/images/Home/exquisite-foods.png'
import amazing_views from '../public/images/Home/amazing-views.png'
import image_20_template from '../public/images/Home/image-20-template.png'
import Diamond_Blue from '../public/images/About/Diamond_Blue.svg'
import left_arrow from '../public/images/Home/left-arrow.png'
import right_arrow from '../public/images/Home/right-arrow.png'
import donts from '../public/images/Home/“.png'



export default function Home() {

  gsap.registerPlugin(ScrollTrigger);

  // Gallery 
  useEffect(() => {
    gsap.to(".effect_1", {
      x: -3700,
      duration: 1,
      ease: 'none',
      scrollTrigger: {
        start: "-=550",
        trigger: ".effect_2",
        toggleActions: "restart pause reverse pause",
        end: '+=1200',
        scrub: 1,
      }
    }
    );
  }, []);

  useEffect(() => {
    gsap.to(".effect_2", {
      x: -3700,
      duration: 1,
      ease: 'none',
      scrollTrigger: {
        start: "-=550",
        trigger: ".effect_2",
        toggleActions: "restart pause reverse pause",
        end: '+=1200',
        scrub: 1,
      }
    }
    );
  }, []);

  useEffect(() => {
    gsap.to(".effect_4", {
      x: -3500,
      duration: 1,
      ease: 'none',
      scrollTrigger: {
        start: "-=520",
        trigger: ".effect_3",
        toggleActions: "restart pause reverse pause",
        end: '+=1100',
        scrub: 1,
      }
    }
    );
  }, []);

  useEffect(() => {
    gsap.to(".effect_3", {
      x: -3500,
      duration: 1,
      ease: 'none',
      scrollTrigger: {
        start: "-=520",
        trigger: ".effect_3",
        toggleActions: "restart pause reverse pause",
        end: '+=1100',
        scrub: 1,
      }
    }
    );
  }, []);


  return (
    <>
      <Head>
        <title>Yelitza & Jesús</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className={style.overflow}>

        <div className={style.page_wrapper}>

          {/* S1 */}
          <div className={style.hero_section}>
            <div className={style.roadmap_shape_left} />
            <div className={style.roadmap_shape_right} />

            <div className={`${style.container} ${style.w_container}`}>
              <div className={style.hero_inner}>
                <div
                  id={style["w-node-_3c19c017-cc3c-97c6-42ec-4a6aba7d1b7d-fbe143f2"]}
                  className={style.hero_top}
                >
                  <div className={style.top_left}>
                    <h1 className={`${style.hero_title} ${style.hero_movil_2} ${style.hero_one}`}>
                      Titulo
                      <br />
                      &nbsp;&nbsp;&nbsp;&nbsp;Titulo&nbsp;
                      <span className={style.capsule}>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      </span>&nbsp;Text
                    </h1>
                    <h1 className={`${style.hero_title} ${style.hero_movil} ${style.hero_one}`}>
                      Titulo
                      <br />
                      &nbsp;&nbsp;&nbsp;&nbsp;Titulo&nbsp;
                      <span className={style.capsule}>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      </span>
                      &nbsp;
                      Text
                    </h1>
                    <p className={style.hero_sub_content}>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam ut quidem fugit architecto illo hic neque cum, suscipit
                      nemo doloremque laborum rem numquam exercitationem delectus dolores aliquid laboriosam placeat iusto.
                    </p>
                    <Link
                      href="/"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Ver Portafolio</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                    <Gallery>
                      <Item
                        original="/images/Home/home2_1067x712.jpg"
                        thumbnail="/images/Home/home2_1067x712.jpg"
                        width="1067"
                        height="712"
                      >
                        {({ ref, open }) => (
                          <Image
                            priority={true}
                            ref={ref}
                            onClick={open}
                            src={home_2}
                            loading="eager"
                            alt="Hero Left Image"
                            className={style.hero_circle_image}
                            sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                          />
                        )}
                      </Item>
                    </Gallery>
                  </div>

                  <div className={style.top_right}>
                    {/* <Image
                      src={home_3}
                      loading="eager"
                      sizes="(max-width: 767px) 180px, (max-width: 991px) 250px, 380px"
                      srcSet="https://uploads-ssl.webflow.com/6329a2447290bd1aa8e143f1/6360c972d8ee243c9e58084b_hero-main%20(1)-p-500.jpg 500w, https://uploads-ssl.webflow.com/6329a2447290bd1aa8e143f1/6360c972d8ee243c9e58084b_hero-main%20(1).jpg 766w"
                      width={383}
                      alt="Hero Img"
                      className={style.top_circle_image}
                    /> */}
                    <Gallery>
                      <Item
                        original="/images/Home/home3_1067x712.jpg"
                        thumbnail="/images/Home/home3_1067x712.jpg"
                        width="1067"
                        height="712"
                      >
                        {({ ref, open }) => (
                          <Image
                            priority={true}
                            ref={ref}
                            onClick={open}
                            src={home_3}
                            loading="eager"
                            sizes="(max-width: 767px) 180px, (max-width: 991px) 250px, 380px"
                            width={383}
                            alt="Hero Img"
                            className={style.top_circle_image} />
                        )}
                      </Item>
                    </Gallery>
                  </div>
                </div>
                <div
                  id={style["w-node-_020a1539-09fc-2765-16e8-bf036c940ac5-fbe143f2"]}
                  className={style.hero_bottom}
                >
                  <div className={style.bottom_left}>
                    <div className={style.flex}>
                      <h4 className={style.last_heading}>Titulo</h4>
                      <p className={`${style.body_small} ${style.last_paragraph}`}>Texto de Prueba </p>
                    </div>
                    <div className={style.flex}>
                      <h4 className={style.last_heading}>Titulo</h4>
                      <p className={`${style.body_small} ${style.last_paragraph}`}>
                        Texto de Prueba
                      </p>
                    </div>
                  </div>
                  <div className={style.bottom_right}>
                    {/* <Image
                      src={home_1}
                      loading="eager"
                      alt="Explore Image"
                      className={style.hero_image}
                    /> */}
                    <Gallery>
                      <Item
                        original="/images/Home/home1_853x569.jpg"
                        thumbnail="/images/Home/home1_853x569.jpg"
                        width="853"
                        height="569"
                      >
                        {({ ref, open }) => (
                          <Image
                            priority={true}
                            ref={ref}
                            onClick={open}
                            src={home_1}
                            loading="eager"
                            alt="Explore Image"
                            className={style.hero_image} />
                        )}
                      </Item>
                    </Gallery>
                    <div>
                      <h4 className={style.last_heading}>Titulo Titulo</h4>
                      <p className={style.last_paragraph}>
                        Texto de Prueba Texto de Prueba Texto de Prueba
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* S2 */}
          <div className={style.feature_section}>
            <div className={`${style.container} ${style.w_container}`}>
              <div className={style.featured_inner}>
                <p className={style.subtitle}>VER EL MUNDO CON TUS PROPIOS OJOS</p>
                <h2 className={style.last_heading}>Viaje, Exploración &amp; Aventura</h2>
                <p className={style.subtitle_content}>Text de Prueba Text de Prueba Text de Prueba Text de Prueba </p>

              </div>
            </div>
          </div>

          {/* S3 */}
          <div id="category" className={style.about_section}>
            <div className={`${style.main_content} ${style.about_section_content}`}>
              <div className={style.invitation_holder}>
                <div id={style["category-1"]} className={style.invitation_box}>
                  <a href='#' className={`${style.link_overflow} ${style.link_category}`} >
                    <Image
                      src={stylish_pools}
                      loading="lazy"
                      sizes="(max-width: 479px) 81vw, (max-width: 767px) 80vw, 26vw"
                      alt=""
                      className={style.image_category}
                    />
                  </a>
                  <div className={style.block_category}>
                    <div className={style.info}>
                      <div className={style.horizontal_brown_line} />
                      <h4 className={style.no_margin}>Ceremonia Civil</h4>
                    </div>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam ut quidem fugit architecto illo hic neque cum, suscipit
                      nemo doloremque laborum rem numquam exercitationem delectus dolores aliquid laboriosam placeat iusto.
                    </p>
                    <Link
                      href="/"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Ver Portafolio</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                  </div>

                </div>
                <div id={style["category-2"]} className={style.invitation_box}>
                  <a href='#' className={`${style.link_overflow} ${style.link_category}`} >
                    <Image
                      src={exquisite_foods}
                      loading="lazy"
                      sizes="(max-width: 479px) 81vw, (max-width: 767px) 80vw, 26vw"
                      alt=""
                      className={style.image_category}
                    />
                  </a>
                  <div className={style.block_category}>
                    <div className={style.info}>
                      <div className={style.horizontal_brown_line} />
                      <h4 className={style.no_margin}>Ceremonia Civil</h4>
                    </div>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam ut quidem fugit architecto illo hic neque cum, suscipit
                      nemo doloremque laborum rem numquam exercitationem delectus dolores aliquid laboriosam placeat iusto.
                    </p>
                    <Link
                      href="/"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Ver Portafolio</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                  </div>

                </div>
                <div id={style["category-3"]} className={style.invitation_box}>
                  <a href='#' className={`${style.link_overflow} ${style.link_category}`} >
                    <Image
                      src={amazing_views}
                      loading="lazy"
                      sizes="(max-width: 479px) 81vw, (max-width: 767px) 80vw, 26vw"
                      alt=""
                      className={style.image_category}
                    />
                  </a>
                  <div className={style.block_category}>
                    <div className={style.info}>
                      <div className={style.horizontal_brown_line} />
                      <h4 className={style.no_margin}>Ceremonia Civil</h4>
                    </div>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam ut quidem fugit architecto illo hic neque cum, suscipit
                      nemo doloremque laborum rem numquam exercitationem delectus dolores aliquid laboriosam placeat iusto.
                    </p>
                    <Link
                      href="/"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Ver Portafolio</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                  </div>


                </div>
              </div>
            </div>
          </div>

          {/* Video */}
          <div className={`${style.section} ${style.padding_0}`}>
            <div className={style.container_large}>
              <div className={`${style.column_xlarge} ${style.text_align_center}`}>
                <div className={style.video_contain}>
                  <div
                    className={`${style.video_home} ${style.w_background_video} ${style.w_background_video_atom}`}
                    style={{ width: "100%", height: "100%" }}
                  >
                    <video
                      id="32d20bf2-808b-659a-4433-133edaba0c6d-video"
                      autoPlay={true}
                      loop
                      style={{
                        backgroundImage:
                          'url("https://assets.website-files.com/625a7fd81dde5ff598e46825/626286e5774f0992162467d8_hm-hero-light-poster-00001.jpg")'
                      }}
                      muted
                      playsInline
                    >
                      <source
                        src="https://assets.website-files.com/625a7fd81dde5ff598e46825/626286e5774f0992162467d8_hm-hero-light-transcode.mp4"
                        data-wf-ignore="true"
                      />
                      <source
                        src="https://assets.website-files.com/625a7fd81dde5ff598e46825/626286e5774f0992162467d8_hm-hero-light-transcode.webm"
                        data-wf-ignore="true"
                      />
                    </video>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Ella */}
          <div id={style['history-1']} className={style.blue_section}>
            <div className={style.container}>
              <h2 className={style.centered}>
                Ella
              </h2>
              <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                <Image
                  src={Diamond_Blue}
                  loading="lazy"
                  alt=""
                />
                <div className={`${style.decorative_line} ${style.blue}`} />
              </div>
              <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
            </div>
            <div className={`${style.container} ${style.with_columns}`}>
              <div className={`${style._2_columns} ${style.image_on_right} ${style.w_row}`}>
                <div className={`${style.column} ${style.centered} ${style.w_col} ${style.w_col_5}`}>
                  <div className={style.centered_column_content}>
                    <h3 className={style.left_aligned}>Historia de Ella</h3>
                    <p className={style.left_aligned}>
                      Enjoy a finely curated meal and upscale atmosphere in our bar and
                      restaurant. Our philosophy for food and drinks matches our
                      hospitality philosophy for our suites. We strive for perfection. Our
                      ingredients are locally sourced and inspired. Our drinks are the
                      creative magic of our skilled mixologists.
                    </p>
                    <Link
                      href="/About"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Saber Más</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                  </div>
                </div>
                <div className={`${style.overlapping_images_column} ${style.w_col} ${style.w_col_7}`}>
                  <div className={`${style.overlapping_column_image} ${style.overlapping_front}`} />
                  <div className={`${style.overlapping_back_image_div} ${style.overlapping_bottom_image_right}`}>
                    <div className={style.overlapping_column_image} />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Gallery */}
          <div id={style['history-1']} className={`${style.padding_vertical} ${style.padding_huge}`}>
            <div className={style.container}>
              <h2 className={style.centered}>
                Gallery
              </h2>
              <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                <Image
                  src={Diamond_Blue}
                  loading="lazy"
                  alt=""
                />
                <div className={`${style.decorative_line} ${style.blue}`} />
              </div>
              <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
            </div>
            <div className={style.row_image_wrapper}>
              <div className={style.header_row}>
                <div className={style.row_wrapper_reverse}>
                  <div className={`effect_3 ${style.w_layout_grid} ${style.row_component}`}>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                  </div>
                </div>
                <div className={style.row_wrapper_reverse}>
                  <div className={`effect_4 ${style.w_layout_grid} ${style.row_component}`}>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.header_row}>
                <div className={style.row_wrapper}>
                  <div className={`effect_1 ${style.w_layout_grid} ${style.row_component}`}>
                    {/* <div>
                      
                    </div> */}
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                  </div>
                </div>
                <div className={style.row_wrapper}>
                  <div className={`effect_2 ${style.w_layout_grid} ${style.row_component}`}>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                    <div
                      id={style["w-node-_3b1f5c82-e522-f04c-2bcb-bb12bb8eb423-a518d5e4"]}
                      className={style.row_image_overflow}
                    >
                      <Image
                        src={image_20_template}
                        loading="lazy"
                        sizes="(max-width: 479px) 40vw, (max-width: 767px) 30vw, 25vw"
                        alt="Licensed Image - Portrait Webflow Template"
                        className={style.cover_image}
                      />
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>

          {/* El */}
          <div id={style['history-2']} className={style.blue_section}>
            <div className={style.container}>
              <h2 className={style.centered}>
                Él
              </h2>
              <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                <Image
                  src={Diamond_Blue}
                  loading="lazy"
                  alt=""
                />
                <div className={`${style.decorative_line} ${style.blue}`} />
              </div>
              <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
            </div>
            <div className={`${style.container} ${style.with_columns}`}>
              <div className={`${style._2_columns} ${style.w_row}`}>
                <div className={`${style.overlapping_images_column} ${style.left} ${style.w_col} ${style.w_col_7}`}>
                  <div className={`${style.overlapping_column_image} ${style.overlapping_front_weddings}`} />
                  <div className={`${style.overlapping_back_image_div} ${style.overlapping_bottom_image_left}`}>
                    <div className={`${style.overlapping_column_image} ${style.weddings}`} />
                  </div>
                </div>
                <div className={`${style.column} ${style.centered} ${style.w_col} ${style.w_col_5}`}>
                  <div className={style.centered_column_content}>
                    <h3 className={style.left_aligned}>
                      Historia Sobre Él
                    </h3>
                    <p className={style.left_aligned}>
                      Text de Prueba Text de Prueba Text de Prueba
                      Text de Prueba Text de Prueba Text de Prueba Text de Prueba
                      Text de Prueba Text de Prueba Text de Prueba Text de Prueba
                      Text de Prueba Text de Prueba Text de Prueba
                    </p>
                    <Link
                      href="/About"
                      className={`${style.book_now_link} ${style.w_inline_block}`}
                    >
                      <p className={style.subtitle}>Saber Más</p>
                      <Image
                        src={arrow}
                        loading="lazy"
                        alt="Arrow"
                        className={style.arrow_image}
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Testimonials */}
          <div id={style['history-1']} className={style.testimonials}>
            <div className={`${style.main_content} ${style.testimonials_content}`}>
              <div className={style.container}>
                <h2 className={style.centered}>
                  Que dicen
                  <br />
                  sobre ellos
                </h2>
                <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                  <Image
                    src={Diamond_Blue}
                    loading="lazy"
                    alt=""
                  />
                  <div className={`${style.decorative_line} ${style.blue}`} />
                </div>
                <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
              </div>
              <div className={`${style.testimonials_slider} ${style.w_slider}`}>
                <div
                  className={`${style.testimonials_slider_mask} ${style.w_slider_mask}`}
                  id="w-slider-mask-0"
                >
                  <div className={`${style.slide} ${style.w_slide}`}>
                    <div className={style.qq}>
                      <Image
                        src={donts}
                        loading="lazy"
                        alt=""
                      />
                    </div>
                    <p className={style.quote}>
                      <em>
                        Texto de Prueba
                      </em>
                    </p>
                    <p className={style.normal_margin}>
                      Texto de Prueba texto de Prueba texto de Prueba texto de Prueba texto de Prueba
                      texto de Prueba texto de Prueba texto de Prueba texto de Prueba texto de Prueba
                    </p>
                    <div className={style.author_wrapper}>
                      <p className={style.author_name}>
                        Nombre
                      </p>
                      <p>Familiar</p>
                    </div>
                  </div>
                </div>
                <div className={`${style.left_arow} ${style.w_slider_arrow_left}`}>
                  <Image
                    src={left_arrow}
                    loading="lazy"
                    alt=""
                    className={style.left_arrow_icon}
                  />
                </div>
                <div className={`${style.right_arrow} ${style.w_slider_arrow_right}`}>
                  <Image
                    src={right_arrow}
                    loading="lazy"
                    alt=""
                    className={style.right_arrow_icon}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Portafolio
https://fortitude-template.webflow.io/resorts */}

          {/* About 
https://travigo.webflow.io/blog/hispanic-heritage-in-these-culturally-rich-locales-in-greece */}

        </div>

        <Footer />

      </div>
    </>
  )
}
