import Head from 'next/head'
import React, { useLayoutEffect } from 'react'
import { gsap, Linear } from "gsap";
import Image from 'next/image';
import Link from 'next/link';


import style from '@/styles/Home.module.css'

import Footer from './components/Footer';

// Images
import Diamond_Blue from '../public/images/About/Diamond_Blue.svg'
import resort_hero_lt from '../public/images/Portfolio/resort-hero-lt.jpg'
import resort_hero_rt from '../public/images/Portfolio/resort-hero-rt.jpg'
import badge_hotel from '../public/images/Portfolio/badge-hotel.svg'
import resort_06 from '../public/images/Portfolio/resort-06.jpg'


export default function Portfolio() {

    useLayoutEffect(() => {
        gsap.to(".rotation", 3, {
            ease: Linear.easeNone,
            repeat: -2,
            rotation: "+=360",
            duration: 1,
            onComplete: () => loop.play()
        });
        return;
    }, []);

    return (
        <>

            <Head>
                <title>Portafolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={style.overflow}>

                {/* S1 */}
                <div className={`${style.section} ${style.home_hero}`}>
                    <div className={style.container_large}>
                        <div id={style['Portfolio-1']}>
                            <div className={style.container}>
                                <h2 className={style.centered}>
                                    Portafolio
                                </h2>
                                <div className={`${style.decorative_line_flipped_div} ${style.blue}`}>
                                    <Image
                                        src={Diamond_Blue}
                                        loading="lazy"
                                        alt=""
                                    />
                                    <div className={`${style.decorative_line} ${style.blue}`} />
                                </div>
                                <div className={`${style.all_caps} ${style.centered}`}>Apellido - Apellido</div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* S2 */}
                <div className={`${style.section} ${style.hero_full}`}>
                    <div className={`${style.grid_halves} ${style.store}`}>
                        <div
                            id={style["w-node-a1eb7a7b-9907-74d3-4797-68d70a3872d3-6bcd54c3"]}
                            className={style.store_hero_left_mask}
                        >
                            <Image
                                src={resort_hero_lt}
                                loading="eager"
                                id={style["w-node-_3f4f55ad-9fe0-cf9e-ae45-9ca59c89d79e-6bcd54c3"]}
                                style={{ width: "100%", height: "100%" }}
                                sizes="50vw"
                                alt=""
                                className={style.store_hero_left}
                            />
                        </div>
                        <div
                            id={style["w-node-_6722be16-07d8-aefe-bb7b-ea5fa13bd5a6-6bcd54c3"]}
                            className={style.store_hero_right_mask}
                        >
                            <Image
                                src={resort_hero_rt}
                                loading="eager"
                                style={{ width: "100%", height: "100%" }}
                                id={style["w-node-_1d3b6d84-7388-ac37-b821-81a773afc34e-6bcd54c3"]}
                                sizes="50vw"
                                alt=""
                                className={style.store_hero_right}
                            />
                        </div>
                    </div>
                    <div className={style.badge_hotel_wrap}>
                        <Image
                            src={badge_hotel}
                            loading="lazy"
                            alt=""
                            className={`rotation ${style.badge_hotel}`}
                        />
                    </div>
                </div>

                {/* S3 */}
                <div id={style["Gallery"]} className={style.section}>
                    <div className={style.container}>
                        <div className={style.w_dyn_list}>
                            <div className={`${style.grid_halves} ${style.room_list} ${style.w_dyn_items}`}>
                                <div className={style.w_dyn_item}>
                                    <Link
                                        href="/"
                                        className={`${style.room_item} ${style.w_inline_block}`}
                                    >
                                        <div className={`${style.room_thumb} ${style.margin_24}`}>
                                            <Image
                                                src={resort_06}
                                                loading="lazy"
                                                alt=""
                                                className={style.room_thumb_image}
                                            />
                                        </div>
                                        <h2 className={`${style.heading_small} ${style.margin_12}`}>Titulo</h2>
                                        <div className={style.room_text}>
                                            <p className={`${style.text_color_light} ${style.margin_12}`}>
                                                Text de Prueba Text de Prueba Text de Prueba Text de Prueba
                                                Text de Prueba
                                            </p>
                                        </div>
                                    </Link>
                                </div>
                                <div className={style.w_dyn_item}>
                                    <Link
                                        href="/"
                                        className={`${style.room_item} ${style.w_inline_block}`}
                                    >
                                        <div className={`${style.room_thumb} ${style.margin_24}`}>
                                            <Image
                                                src={resort_06}
                                                loading="lazy"
                                                alt=""
                                                className={style.room_thumb_image}
                                            />
                                        </div>
                                    </Link>
                                </div>
                                <div className={style.w_dyn_item}>
                                    <Link
                                        href="/"
                                        className={`${style.room_item} ${style.w_inline_block}`}
                                    >
                                        <div className={`${style.room_thumb} ${style.margin_24}`}>
                                            <Image
                                                src={resort_06}
                                                loading="lazy"
                                                alt=""
                                                className={style.room_thumb_image}
                                            />
                                        </div>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <Footer />

            </div>

        </>
    )
}
